name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: |
            Frontend/package-lock.json
            package-lock.json

      - name: Clean and install dependencies
        run: |
          rm -rf node_modules Frontend/node_modules Backend/node_modules || true
          rm -f package-lock.json Frontend/package-lock.json || true
          npm install --include=optional --no-audit --no-fund

      - name: Build Frontend
        working-directory: Frontend
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          NODE_OPTIONS: '--max-old-space-size=4096'
        run: npm run build

      - name: Debug - Check deployment setup
        run: |
          echo "🔍 DEBUGGING AZURE SWA DEPLOYMENT"
          echo "=================================="
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Working Directory Structure:"
          ls -la
          echo ""
          echo "Frontend Directory:"
          ls -la Frontend/
          echo ""
          echo "Build Output (Frontend/dist):"
          ls -la Frontend/dist/ || echo "❌ No dist directory found!"
          echo ""
          echo "Checking for index.html:"
          test -f Frontend/dist/index.html && echo "✅ index.html found" || echo "❌ index.html missing"
          echo ""
          echo "Checking for staticwebapp.config.json:"
          test -f Frontend/staticwebapp.config.json && echo "✅ staticwebapp.config.json found in Frontend/" || echo "❌ staticwebapp.config.json missing"
          echo ""
          echo "API Token length check:"
          echo "Token length: ${#AZURE_TOKEN}"
          echo "Token starts with: ${AZURE_TOKEN:0:10}..."
          echo ""
          echo "Testing API Token with a simple request:"
          if [ -n "$AZURE_TOKEN" ]; then
            echo "✅ Token is present"
            # Try to make a simple request to validate the token
            curl -s -X POST "https://api.azurestaticapps.net/api/v1/sites" \
              -H "Authorization: Bearer $AZURE_TOKEN" \
              -H "Content-Type: application/json" \
              -w "\nHTTP Status: %{http_code}\n" \
              --max-time 30 || echo "❌ Token test failed"
          else
            echo "❌ Token is empty or not set!"
          fi
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_OCEAN_045BB2410 }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_OCEAN_045BB2410 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Frontend"
          output_location: "dist"
          skip_app_build: true
        continue-on-error: true
        id: swa_deploy

      - name: Debug - Show deployment result
        if: always()
        run: |
          echo "🔍 DEPLOYMENT RESULT DEBUG"
          echo "========================="
          echo "Deployment step outcome: ${{ steps.swa_deploy.outcome }}"
          echo "Deployment step conclusion: ${{ steps.swa_deploy.conclusion }}"
          if [ "${{ steps.swa_deploy.outcome }}" != "success" ]; then
            echo "❌ Deployment failed - this gives us the specific error details above"
            echo "Common fixes to try:"
            echo "1. Check if the Azure Static Web App still exists in Azure Portal"
            echo "2. Regenerate the API token in Azure Portal"
            echo "3. Update the GitHub secret with the new token"
            echo "4. Verify the app_location and output_location paths"
            exit 1
          else
            echo "✅ Deployment succeeded!"
          fi

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_OCEAN_045BB2410 }}
          action: "close"