name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Code Quality & Testing
  quality:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: Frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./Frontend
      run: npm ci
      
    - name: Type checking
      working-directory: ./Frontend
      run: npm run type-check
      
    - name: Lint code
      working-directory: ./Frontend
      run: npm run lint
      
    - name: Check code formatting
      working-directory: ./Frontend
      run: npm run format:check
      
    - name: Run tests
      working-directory: ./Frontend
      run: npm run test:coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./Frontend/coverage
        flags: frontend
        name: codecov-frontend
        
  # Security Audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: Frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./Frontend
      run: npm ci
      
    - name: Run security audit
      working-directory: ./Frontend
      run: npm audit --audit-level moderate
      
    - name: Check for known vulnerabilities
      uses: securecodewarrior/github-action-add-sarif@v1
      with:
        sarif-file: 'audit-results.sarif'
      continue-on-error: true
      
  # Build & Deploy
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [quality, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: Frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./Frontend
      run: npm ci
      
    - name: Build application
      working-directory: ./Frontend
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: Frontend/dist/
        retention-days: 30
        
  # Performance Testing
  performance:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: Frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./Frontend
      run: npm ci
      
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-files
        path: Frontend/dist/
        
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v10
      with:
        configPath: './Frontend/lighthouserc.json'
        uploadArtifacts: true
        temporaryPublicStorage: true
        
  # Deployment (only on main branch)
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [quality, security, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    environment:
      name: production
      url: https://your-domain.com
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-files
        path: Frontend/dist/
        
    - name: Deploy to production
      run: |
        echo "🚀 Deploying to production..."
        # Add your deployment commands here
        # Examples:
        # - Deploy to Vercel: vercel --prod
        # - Deploy to Netlify: netlify deploy --prod
        # - Deploy to AWS S3: aws s3 sync dist/ s3://your-bucket/
        # - Deploy to your server via SSH/SCP
        echo "✅ Deployment completed!"
        
    - name: Create deployment notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        text: '🚀 Production deployment completed!'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()