# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - marketplace-backend-prod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org/'

      - name: Verify project structure
        run: |
          echo "Verifying project structure..."
          echo "Current directory: $(pwd)"
          echo "Root package.json exists: $(test -f package.json && echo 'YES' || echo 'NO')"
          echo "Backend directory exists: $(test -d Backend && echo 'YES' || echo 'NO')"
          echo "Backend package.json exists: $(test -f Backend/package.json && echo 'YES' || echo 'NO')"
          echo "Workspace configuration:"
          cat package.json | grep -A 5 "workspaces"

      - name: Install all dependencies (workspace)
        run: |
          set -e
          echo "Installing dependencies for the entire workspace..."
          echo "Current working directory: $(pwd)"
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          
          # Install all dependencies including workspaces
          npm ci --ignore-scripts --no-audit --no-fund
          
          echo "All dependencies installed successfully"
          echo "Installed packages in root:"
          npm list --depth=0
          echo "Installed packages in Backend:"
          npm list --depth=0 --workspace=Backend
        env:
          CI: true
          HUSKY: 0

      - name: Build Backend application (optimized)
        run: |
          echo "Starting Backend optimized build process..."
          cd Backend
          npm run build:optimized
          echo "Build completed successfully"
          
          # Verify build output
          echo "Build output contents:"
          ls -la dist/
        env:
          CI: true
          NODE_ENV: production

      - name: Create production deployment package
        run: |
          echo "Creating production deployment package..."
          
          # Create clean deployment directory
          mkdir -p deployment
          
          # Copy only production files from Backend
          echo "Copying production files..."
          cp -r Backend/dist deployment/
          cp Backend/package.json deployment/
          
          # Create a minimal package.json for production
          echo "Creating production package.json..."
          cd deployment
          
          # Extract only production dependencies
          node -e "
            const pkg = require('./package.json');
            const prodDeps = {};
            
            // Keep only production dependencies
            if (pkg.dependencies) {
              Object.keys(pkg.dependencies).forEach(key => {
                if (!key.startsWith('@types/') && key !== 'tsx' && key !== 'typescript') {
                  prodDeps[key] = pkg.dependencies[key];
                }
              });
            }
            
            // Create new package.json
            const newPkg = {
              name: pkg.name,
              version: pkg.version,
              private: pkg.private,
              type: pkg.type,
              scripts: {
                start: pkg.scripts.start
              },
              dependencies: prodDeps
            };
            
            require('fs').writeFileSync('./package.json', JSON.stringify(newPkg, null, 2));
            console.log('Production package.json created with dependencies:', Object.keys(prodDeps));
          "
          
          # Install only production dependencies using npm install (not npm ci)
          echo "Installing production dependencies..."
          npm install --only=production --no-audit --no-fund
          
          echo "Deployment package created successfully"
          echo "Final package contents:"
          ls -la
          echo "Final dependencies:"
          npm list --depth=0
        env:
          CI: true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'marketplace-backend-prod'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6D9D691DC7CA400DB82578B627BAC9AA }}
