# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - marketplace-backend-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set working directory
        run: echo "Using Backend/ as working directory"
        working-directory: Backend

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm
          cache-dependency-path: Backend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: Backend
        env:
          CI: true
          HUSKY: 0

      - name: Build
        run: npm run build
        working-directory: Backend
        env:
          CI: true

      - name: Prune dev dependencies
        run: npm prune --omit=dev
        working-directory: Backend

      - name: Upload artifact for deployment job (Backend only)
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'marketplace-backend-prod'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6D9D691DC7CA400DB82578B627BAC9AA }}