# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - marketplace-backend-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set working directory
        run: echo "Using Backend/ as working directory"
        working-directory: Backend

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm
          cache-dependency-path: Backend/package-lock.json
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure npm for better reliability
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm config set fetch-timeout 300000
        working-directory: Backend

      - name: Install dependencies with retry
        run: |
          set -e
          max_attempts=3
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts"
            if npm ci --ignore-scripts --prefer-offline --no-audit; then
              echo "Dependencies installed successfully on attempt $attempt"
              break
            else
              if [ $attempt -eq $max_attempts ]; then
                echo "Failed to install dependencies after $max_attempts attempts"
                exit 1
              fi
              echo "Attempt $attempt failed, waiting before retry..."
              sleep $(( attempt * 30 ))
              ((attempt++))
            fi
          done
        working-directory: Backend
        env:
          CI: true
          HUSKY: 0
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build with error handling
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed successfully"
        working-directory: Backend
        env:
          CI: true
          NODE_ENV: production

      - name: Prune dev dependencies
        run: |
          echo "Pruning development dependencies..."
          npm prune --omit=dev --no-audit
          echo "Development dependencies pruned successfully"
        working-directory: Backend

      - name: Upload artifact for deployment job (Backend only)
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'marketplace-backend-prod'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6D9D691DC7CA400DB82578B627BAC9AA }}