# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - marketplace-backend-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org/'

      - name: Verify project structure
        run: |
          echo "Verifying project structure..."
          echo "Current directory: $(pwd)"
          echo "Root package.json exists: $(test -f package.json && echo 'YES' || echo 'NO')"
          echo "Backend directory exists: $(test -d Backend && echo 'YES' || echo 'NO')"
          echo "Backend package.json exists: $(test -f Backend/package.json && echo 'YES' || echo 'NO')"
          echo "Workspace configuration:"
          cat package.json | grep -A 5 "workspaces"

      - name: Install all dependencies (workspace)
        run: |
          set -e
          echo "Installing dependencies for the entire workspace..."
          echo "Current working directory: $(pwd)"
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          
          # Install all dependencies including workspaces
          npm ci --ignore-scripts --no-audit --no-fund
          
          echo "All dependencies installed successfully"
          echo "Installed packages in root:"
          npm list --depth=0
          echo "Installed packages in Backend:"
          npm list --depth=0 --workspace=Backend
        env:
          CI: true
          HUSKY: 0

      - name: Build Backend application
        run: |
          echo "Starting Backend build process..."
          cd Backend
          npm run build
          echo "Build completed successfully"
          
          # Verify build output
          echo "Build output contents:"
          ls -la dist/
        env:
          CI: true
          NODE_ENV: production

      - name: Prepare Backend for deployment
        run: |
          echo "Preparing Backend for deployment..."
          cd Backend
          
          # Remove dev dependencies from Backend only
          echo "Removing dev dependencies from Backend..."
          npm prune --omit=dev --no-audit
          
          echo "Backend prepared successfully"
          echo "Final Backend dependencies:"
          npm list --depth=0
          
          # Copy Backend to a clean directory for deployment
          cd ..
          mkdir -p deployment
          cp -r Backend/* deployment/
          
          echo "Deployment package prepared:"
          ls -la deployment/
        env:
          CI: true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'marketplace-backend-prod'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6D9D691DC7CA400DB82578B627BAC9AA }}